name: telecom_dashboard
description: Личный кабинет телеком-абонента — Flutter Clean Architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.2.0

  # Networking
  dio: ^5.4.3

  # Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.12.0
  fpdart: ^1.1.0

  # Local storage
  shared_preferences: ^2.2.3

  # Biometric auth
  local_auth: ^2.3.0

  # Utils / Localization
  intl: any

  flutter_localizations:
    sdk: flutter

  # Icons
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: any
  freezed: any
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
