name: telecom_dashboard
description: Личный кабинет телеком-абонента — Flutter Clean Architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^14.2.0

  # Networking
  dio: ^5.4.3

  # Serialization
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  fpdart: ^1.1.0

  # Local storage
  shared_preferences: ^2.2.3

  # Utils
  intl: ^0.19.0

  # Icons
  lucide_icons: ^0.377.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
